# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=2g -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# AndroidX settings
android.useAndroidX=true
android.enableJetifier=true
kotlin.daemon.jvm.options=-Xmx2048M

